// <auto-generated />
namespace Proyecto.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_01));
        
        string IMigrationMetadata.Id
        {
            get { return "202406140152349_01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
