//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBD_3._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriasProductos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoriasProductos()
        {
            this.SubCategoriasProductos = new HashSet<SubCategoriasProductos>();
        }
    
        public long ID_CategoriaProducto { get; set; }
        public long NO_CategoriaProducto { get; set; }
        public string Codigo_CategoriaProducto { get; set; }
        public string Descripcion_CategoriaProducto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubCategoriasProductos> SubCategoriasProductos { get; set; }
    }
}
