//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBD_3._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosUsuarios
    {
        public long ID_DatoUsuario { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public short Edad { get; set; }
        public long ID_NumTelefono { get; set; }
        public long ID_Genero { get; set; }
        public long ID_DocumentoIdentidad { get; set; }
    
        public virtual NumerosTelefonicos NumerosTelefonicos { get; set; }
        public virtual Genero Genero { get; set; }
        public virtual DocumentoIdentidad DocumentoIdentidad { get; set; }
    }
}
