//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBD_3._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Entradas
    {
        public long ID_DetalleEntrada { get; set; }
        public long Cantidad_DetalleEntrada { get; set; }
        public long Precio_DetalleEntrada { get; set; }
        public long ID_Entrada { get; set; }
        public long ID_Producto { get; set; }
    
        public virtual Entradas Entradas { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
