//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBD_3._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoIdentidad
    {
        public long ID_DocumentoIdentidad { get; set; }
        public string Codigo_DocumentoIdentidad { get; set; }
        public System.DateTime FechaEmision_DocumentoIdentidad { get; set; }
        public System.DateTime FechaFinalizacion_DocumentoIdentidad { get; set; }
        public long ID_TipoDocumentoIdentidad { get; set; }
    
        public virtual DatosUsuarios DatosUsuarios { get; set; }
        public virtual Tipo_DocumentoIdentidad Tipo_DocumentoIdentidad { get; set; }
    }
}
