//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBD_3._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados : DatosUsuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleados()
        {
            this.Entradas = new HashSet<Entradas>();
            this.Salidas = new HashSet<Salidas>();
        }
    
        public long ID_Empleado { get; set; }
        public long NO_Empleado { get; set; }
        public string Codigo_Empleado { get; set; }
        public string NO_INSS { get; set; }
        public bool Estado_Empleado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entradas> Entradas { get; set; }
        public virtual Tiendas Tiendas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salidas> Salidas { get; set; }
    }
}
