//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBD_3._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresasTelefonicas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmpresasTelefonicas()
        {
            this.NumerosTelefonicos = new HashSet<NumerosTelefonicos>();
        }
    
        public long ID_EmpresaTelefonica { get; set; }
        public long NO_EmpresaTelefonica { get; set; }
        public string Nombre_EmpresaTelefonica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NumerosTelefonicos> NumerosTelefonicos { get; set; }
    }
}
