//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBD_3._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entradas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entradas()
        {
            this.Detalle_Entrada = new HashSet<Detalle_Entradas>();
        }
    
        public long ID_Entrada { get; set; }
        public long NO_Entrada { get; set; }
        public string CodigoEntrada { get; set; }
        public System.DateTime FechaEntrada { get; set; }
        public long ID_Proveedor { get; set; }
        public long ID_TipoEntrada { get; set; }
        public long ID_PagoEntrada { get; set; }
        public long ID_Empleado { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual Tiendas Tiendas { get; set; }
        public virtual Proveedores Proveedores { get; set; }
        public virtual TipoEntrada TipoEntrada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Entradas> Detalle_Entrada { get; set; }
    }
}
