//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBD_3._0.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeloBDContainer : DbContext
    {
        public ModeloBDContainer()
            : base("name=ModeloBDContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Genero> GeneroSet { get; set; }
        public virtual DbSet<Paises> PaisesSet { get; set; }
        public virtual DbSet<Tiendas> TiendasSet { get; set; }
        public virtual DbSet<NumerosTelefonicos> NumerosTelefonicosSet { get; set; }
        public virtual DbSet<EmpresasTelefonicas> EmpresasTelefonicasSet { get; set; }
        public virtual DbSet<DatosUsuarios> DatosUsuariosSet { get; set; }
        public virtual DbSet<Tipo_DocumentoIdentidad> Tipo_DocumentoIdentidadSet { get; set; }
        public virtual DbSet<DocumentoIdentidad> DocumentoIdentidadSet { get; set; }
        public virtual DbSet<Entradas> EntradasSet { get; set; }
        public virtual DbSet<Detalle_Entradas> Detalle_EntradasSet { get; set; }
        public virtual DbSet<Proveedores> ProveedoresSet { get; set; }
        public virtual DbSet<Productos> ProductosSet { get; set; }
        public virtual DbSet<UnidadesMedidas> UnidadesMedidasSet { get; set; }
        public virtual DbSet<TipoEntrada> TipoEntradaSet { get; set; }
        public virtual DbSet<CategoriasProductos> CategoriasProductosSet { get; set; }
        public virtual DbSet<SubCategoriasProductos> SubCategoriasProductosSet { get; set; }
        public virtual DbSet<MarcasProductos> MarcasProductosSet { get; set; }
        public virtual DbSet<Salidas> SalidasSet { get; set; }
        public virtual DbSet<TipoSalida> TipoSalidaSet { get; set; }
        public virtual DbSet<Detalle_Salidas> Detalle_SalidasSet { get; set; }
    }
}
