//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBD_3._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumerosTelefonicos
    {
        public long ID_NumTelefono { get; set; }
        public string NumeroTelefono { get; set; }
        public long ID_EmpresaTelefonica { get; set; }
    
        public virtual Tiendas Tiendas { get; set; }
        public virtual EmpresasTelefonicas EmpresaTelefonica { get; set; }
        public virtual DatosUsuarios DatosUsuarios { get; set; }
    }
}
