//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBD_3._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paises
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paises()
        {
            this.Tipo_DocumentoIdentidad = new HashSet<Tipo_DocumentoIdentidad>();
        }
    
        public long ID_Pais { get; set; }
        public long NO_Pais { get; set; }
        public string Codigo_Pais { get; set; }
        public string Nombre_Pais { get; set; }
        public string Nacionalidad { get; set; }
        public string Sufijo_Pais { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tipo_DocumentoIdentidad> Tipo_DocumentoIdentidad { get; set; }
    }
}
