//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBD_3._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.Detalle_Entrada = new HashSet<Detalle_Entradas>();
            this.Detalle_Salidas = new HashSet<Detalle_Salidas>();
        }
    
        public long ID_Producto { get; set; }
        public string Codigo_Producto { get; set; }
        public string Nombre_Producto { get; set; }
        public long ID_MarcaProducto { get; set; }
        public long ID_UnidadMedida { get; set; }
        public long ID_SubCategoriaProducto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Entradas> Detalle_Entrada { get; set; }
        public virtual UnidadesMedidas UnidadesMedidas { get; set; }
        public virtual MarcasProductos MarcasProductos { get; set; }
        public virtual SubCategoriasProductos SubCategoriasProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Salidas> Detalle_Salidas { get; set; }
    }
}
