//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBD_3._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salidas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Salidas()
        {
            this.Detalle_Salidas = new HashSet<Detalle_Salidas>();
        }
    
        public long ID_Salida { get; set; }
        public long NO_Salida { get; set; }
        public string CodigoSalida { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public long ID_TipoSalida { get; set; }
        public long ID_Empleado { get; set; }
        public long ID_Cliente { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual TipoSalida TipoSalida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Salidas> Detalle_Salidas { get; set; }
        public virtual Tiendas Tiendas { get; set; }
    }
}
