//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBD_3._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tiendas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tiendas()
        {
            this.Empleados = new HashSet<Empleados>();
            this.NumerosTelefonicos = new HashSet<NumerosTelefonicos>();
            this.Entradas = new HashSet<Entradas>();
            this.Salidas = new HashSet<Salidas>();
        }
    
        public long ID_Tienda { get; set; }
        public long NO_Tienda { get; set; }
        public string Codigo_Tienda { get; set; }
        public string Nombre_Tienda { get; set; }
        public string Direccion_Tienda { get; set; }
        public long ID_Ciudad { get; set; }
        public long ID_NumTelefono { get; set; }
        public long ID_Entrada { get; set; }
        public long ID_Empleado { get; set; }
        public long ID_Salida { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleados> Empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NumerosTelefonicos> NumerosTelefonicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entradas> Entradas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salidas> Salidas { get; set; }
    }
}
