//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBD_3._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_DocumentoIdentidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tipo_DocumentoIdentidad()
        {
            this.DocumentoIdentidad = new HashSet<DocumentoIdentidad>();
        }
    
        public long ID_TipoDocumentoIdentidad { get; set; }
        public string NO_TipoDocumentoIdentidad { get; set; }
        public string Descripcion_TipoDocumentoIdentidad { get; set; }
        public long ID_Pais { get; set; }
    
        public virtual Paises Paises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoIdentidad> DocumentoIdentidad { get; set; }
    }
}
